name: 'notify-release-end-action'
description: 'notifies slack channels when a production release has completed'
inputs:
  SLACK_WEBHOOK:
    description: 'slack webhook for notification action'
    required: true
  CHANNEL1:
    description: 'First channel to notify'
    required: false
    default: 'devops-prod'
  CHANNEL2:
    description: 'Second channel to notify'
    required: false
    default: 'software'
  CHANGELOG_CHANNEL:
    description: 'Channel to send changelog to'
    required: false
    default: ''
  TOKEN:
    description: 'github token with API access'
    required: true
    default: ''
  MATRIX:
    description: 'matrix of jobs to get status of from previous jobs'
    required: true
    default: ''
  FAILURE_ICON:
    description: 'icon for slack messages if to be used in future actions'
    required: false
    default: ':dumpsterfire:'
  SUCCESS_ICON:
    description: 'icon for slack messages if to be used in future actions'
    required: false
    default: ':white_check_mark:'
runs:
  using: "composite"
  steps:
    - name: results
      id: job
      uses: CumulusDS/job-results-action@master
      if: always()
      with:
        token: ${{ inputs.TOKEN }}
        matrix: ${{ inputs.MATRIX }}
        failureIcon: ${{ inputs.FAILURE_ICON }}
        successIcon: ${{ inputs.SUCCESS_ICON }}
    - name: Slackify changelog to mrkdwn
      id: slackify
      uses: LoveToKnow/slackify-markdown-action@v1.0.0
      if: always()
      with:
        text: ${{ env.changelog }}
    - name: Notify deployment (#${{ inputs.CHANNEL1 }})
      uses: rtCamp/action-slack-notify@v2
      if: always()
      env:
        SLACK_CHANNEL: "${{ inputs.CHANNEL1 }}"
        SLACK_USERNAME: "${{ env.REPO }}"
        SLACK_ICON: "https://upload.wikimedia.org/wikipedia/commons/0/05/HONDA_ASIMO.jpg"
        SLACK_ICON_EMOJI: ":bell:"
        SLACK_COLOR: "#2D50FF"
        MSG_MINIMAL: true
        SLACK_TITLE: "${{ env.VERSION }} Deployment Status:"
        SLACK_MESSAGE: |
          ${{ env.statusMessage }}
        SLACK_FOOTER: ${{ env.changelogUrl }}
        SLACK_WEBHOOK: ${{ inputs.SLACK_WEBHOOK }}
    - name: Notify deployment (#${{ inputs.CHANNEL2 }})
      uses: rtCamp/action-slack-notify@v2
      if: always() && env.FAILURE == 'true'
      env:
        SLACK_CHANNEL: "${{ inputs.CHANNEL2 }}"
        SLACK_USERNAME: "${{ env.REPO }}"
        SLACK_ICON: "https://upload.wikimedia.org/wikipedia/commons/0/05/HONDA_ASIMO.jpg"
        SLACK_ICON_EMOJI: ":bell:"
        SLACK_COLOR: "#2D50FF"
        MSG_MINIMAL: true
        SLACK_TITLE: "${{ env.VERSION }} Deployment Status:"
        SLACK_MESSAGE: |
          ${{ env.statusMessage }}
        SLACK_FOOTER: ${{ env.changelogUrl }}
        SLACK_WEBHOOK: ${{ inputs.SLACK_WEBHOOK }}
    - name: Changelog (#${{ inputs.CHANGELOG_CHANNEL }})
      id: changelog
      uses: rtCamp/action-slack-notify@v2
      if: always() && inputs.CHANGELOG_CHANNEL != ''
      env:
        SLACK_CHANNEL: "${{ inputs.CHANGELOG_CHANNEL }}"
        SLACK_USERNAME: "${{ env.REPO }}"
        SLACK_ICON: "https://upload.wikimedia.org/wikipedia/commons/0/05/HONDA_ASIMO.jpg"
        SLACK_ICON_EMOJI: ":spiral_note_pad:"
        SLACK_COLOR: "#2D50FF"
        MSG_MINIMAL: true
        SLACK_TITLE: "${{ env.VERSION }} Changelog"
        SLACK_MESSAGE: |
          ${{ steps.slackify.outputs.text }}
        SLACK_FOOTER: ${{ env.changelogUrl }}
        SLACK_WEBHOOK: ${{ inputs.SLACK_WEBHOOK }}
